function Hd = Filter_IIR_L_2M
%FILTER_IIR_L_2M Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 22-Jul-2018 12:00:41

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 100;  % Sampling Frequency

N  = 6;  % Order
Fc = 2;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
